language: java

jdk:
  - openjdk8

services:
    # Enable docker service inside travis
    - docker

install:
    # Build the spring boot app and copy the result to the docker folder
    - mvn -U -Dgpg.skip=true test install
